export type ArticleCatalogItem = {
  id: number;
  slug: string;
  title: string;
  category: "Forestry" | "Recovery" | "Method" | "Production" | "Education" | "Use";
  format: "Featured long-form" | "Core lesson";
  featured: boolean;
  time: string;
  summary: string;
  sourceFile: string;
  status: "editorial-review";
};

/* Editorial import manifest.
   The Word files remain source documents; public presentation reads this stable
   metadata shape so a future CMS can replace the collection without changing UI. */
export const articleCatalog: ArticleCatalogItem[] = [
  { id: 1, slug: "paper-isnt-the-problem-waste-is", title: "Paper Isn’t the Problem. Waste Is.", category: "Method", format: "Featured long-form", featured: true, time: "12 min", summary: "A systems view of sourcing, use, recovery and the choices that turn a material into waste.", sourceFile: "Featured_Article_01_Paper_Isn't_the_Problem_W.docx", status: "editorial-review" },
  { id: 2, slug: "why-paper-can-be-sustainable", title: "Why Paper Can Be One of the Most Sustainable Materials", category: "Method", format: "Core lesson", featured: false, time: "7 min", summary: "A clear framework for judging a paper product by evidence rather than by material label alone.", sourceFile: "Standard_Article_02_Why_Paper_Can_Be_One_of_t.docx", status: "editorial-review" },
  { id: 3, slug: "every-sheet-deserves-a-second-life", title: "Every Sheet Deserves a Second Life", category: "Recovery", format: "Core lesson", featured: false, time: "6 min", summary: "How careful use, separation and collection preserve the value already invested in fibre.", sourceFile: "Standard_Article_03_Every_Sheet_Deserves_a_Se.docx", status: "editorial-review" },
  { id: 4, slug: "forests-grow-because-they-are-managed", title: "Forests Grow Because They Are Managed", category: "Forestry", format: "Core lesson", featured: false, time: "8 min", summary: "A closer look at productive landscapes, forest management and the evidence behind responsible fibre.", sourceFile: "Standard_Article_04_Forests_Grow_Because_They.docx", status: "editorial-review" },
  { id: 5, slug: "recycling-paper-giving-fibres-another-chance", title: "Recycling Paper: Giving Fibres Another Chance", category: "Recovery", format: "Core lesson", featured: false, time: "7 min", summary: "What pulping, screening and cleaning do when a used sheet returns to a mill.", sourceFile: "Standard_Article_05_Recycling_Paper_Giving_Fi.docx", status: "editorial-review" },
  { id: 6, slug: "paper-vs-plastic-beyond-headlines", title: "Paper vs Plastic: Looking Beyond the Headlines", category: "Method", format: "Featured long-form", featured: true, time: "14 min", summary: "Why product, geography, use and end-of-life boundaries matter in material comparisons.", sourceFile: "Featured_Article_06_Paper_vs_Plastic_Looking_.docx", status: "editorial-review" },
  { id: 7, slug: "circular-journey-of-a-sheet", title: "The Circular Journey of a Sheet of Paper", category: "Recovery", format: "Core lesson", featured: false, time: "8 min", summary: "Follow one sheet from use to collection, repulping, remaking and its next useful purpose.", sourceFile: "Standard_Article_07_The_Circular_Journey_of_a.docx", status: "editorial-review" },
  { id: 8, slug: "responsible-paper-use-supports-forestry", title: "Why Responsible Paper Use Supports Sustainable Forestry", category: "Forestry", format: "Core lesson", featured: false, time: "8 min", summary: "Connecting demand, traceable sourcing and long-term management of productive landscapes.", sourceFile: "Standard_Article_08_Why_Responsible_Paper_Use.docx", status: "editorial-review" },
  { id: 9, slug: "zero-paper-waste-campuses", title: "How Schools Can Become Zero Paper Waste Campuses", category: "Education", format: "Core lesson", featured: false, time: "9 min", summary: "A practical campus route through purchasing, full use, separation, collection and measurement.", sourceFile: "Standard_Article_09_How_Schools_Can_Become_Ze.docx", status: "editorial-review" },
  { id: 10, slug: "after-the-paper-bin", title: "What Happens After You Put Paper in the Recycling Bin", category: "Recovery", format: "Core lesson", featured: false, time: "7 min", summary: "The collection, sorting and mill decisions hidden behind a familiar recycling action.", sourceFile: "Standard_Article_10_What_Happens_After_You_Pu.docx", status: "editorial-review" },
  { id: 11, slug: "not-every-paper-recycles-the-same", title: "Why Not Every Paper Should Be Recycled the Same Way", category: "Recovery", format: "Core lesson", featured: false, time: "8 min", summary: "Grades, coatings, contamination and local systems change the route a paper product can take.", sourceFile: "Standard_Article_11_Why_Not_Every_Paper_Shoul.docx", status: "editorial-review" },
  { id: 12, slug: "science-behind-paper-recycling", title: "The Science Behind Paper Recycling", category: "Production", format: "Featured long-form", featured: true, time: "13 min", summary: "Inside hydrapulping, screening, cleaning, de-inking and the fibre losses that shape each cycle.", sourceFile: "Featured_Article_12_The_Science_Behind_Paper_.docx", status: "editorial-review" },
  { id: 13, slug: "cardboard-unsung-recycling-hero", title: "Cardboard: The Unsung Hero of Recycling", category: "Recovery", format: "Core lesson", featured: false, time: "6 min", summary: "Why clean corrugated board is a valuable recovered grade and how to keep it useful.", sourceFile: "Standard_Article_13_Cardboard_The_Unsung_Hero.docx", status: "editorial-review" },
  { id: 14, slug: "recycled-paper-all-around-you", title: "Recycled Paper Is All Around You", category: "Use", format: "Core lesson", featured: false, time: "6 min", summary: "Everyday products that carry recovered fibre—often without calling attention to it.", sourceFile: "Standard_Article_14_Recycled_Paper_Is_All_Aro.docx", status: "editorial-review" },
  { id: 15, slug: "can-we-go-completely-paperless", title: "Can We Really Go Completely Paperless?", category: "Method", format: "Core lesson", featured: false, time: "8 min", summary: "A more useful comparison of material systems, essential uses and the footprint of digital choices.", sourceFile: "Standard_Article_15_Can_We_Really_Go_Complete.docx", status: "editorial-review" },
  { id: 16, slug: "why-using-both-sides-matters", title: "Why Using Both Sides of Paper Matters", category: "Use", format: "Core lesson", featured: false, time: "5 min", summary: "A small behaviour that extends service life before fibre enters a recovery route.", sourceFile: "Standard_Article_16_Why_Using_Both_Sides_of_P.docx", status: "editorial-review" },
  { id: 17, slug: "sustainable-forestry-makes-paper-renewable", title: "Sustainable Forestry Makes Paper Renewable", category: "Forestry", format: "Featured long-form", featured: true, time: "13 min", summary: "What renewability requires from forest management, traceability and credible certification.", sourceFile: "Featured_Article_17_Sustainable_Forestry_Make.docx", status: "editorial-review" },
  { id: 18, slug: "tree-to-notebook-to-new-notebook", title: "From Tree to Notebook to New Notebook", category: "Production", format: "Core lesson", featured: false, time: "8 min", summary: "A complete route from responsibly sourced fibre through manufacture, use and recovery.", sourceFile: "Standard_Article_18_From_Tree_to_Notebook_to_.docx", status: "editorial-review" },
  { id: 19, slug: "smart-paper-choices-homes-offices", title: "Smart Paper Choices for Homes and Offices", category: "Use", format: "Core lesson", featured: false, time: "7 min", summary: "A practical checklist for specification, use, reuse and clean collection.", sourceFile: "Standard_Article_19_Smart_Paper_Choices_for_H.docx", status: "editorial-review" },
  { id: 20, slug: "future-of-paper-circular-economy", title: "The Future of Paper in a Circular Economy", category: "Method", format: "Featured long-form", featured: true, time: "14 min", summary: "Design, collection, producer responsibility and innovation in a lower-waste paper system.", sourceFile: "Featured_Article_20_The_Future_of_Paper_in_a_.docx", status: "editorial-review" },
];

export const featuredArticles = articleCatalog.filter(article => article.featured);
