export type ResourceEntry = {
  title: string;
  type: "Report" | "Guide" | "Standard" | "Data portal" | "Toolkit" | "Research";
  source: "Government" | "Intergovernmental" | "Standards body";
  publisher: string;
  date: string;
  description: string;
  format: string;
  href: string;
  accent: "green" | "copper" | "sage" | "kraft";
};

export const resourceCatalog: ResourceEntry[] = [
  { title:"India State of Forest Report", type:"Report", source:"Government", publisher:"Forest Survey of India", date:"Latest edition", description:"India’s official biennial assessment of forest and tree cover, growing stock, carbon stock and related indicators.", format:"REPORT / DATA", href:"https://fsi.nic.in/forest-report-2023", accent:"green" },
  { title:"Forest Survey of India publications", type:"Data portal", source:"Government", publisher:"Forest Survey of India", date:"Living archive", description:"The publication catalogue for national forest inventories, thematic studies and state-level forest information.", format:"WEB ARCHIVE", href:"https://fsi.nic.in/publications", accent:"sage" },
  { title:"India Forest Data Portal", type:"Data portal", source:"Government", publisher:"Forest Survey of India", date:"Living portal", description:"Official maps and forest-information tools for reading India’s forest landscape beyond a single headline number.", format:"INTERACTIVE DATA", href:"https://fsi.nic.in/", accent:"green" },
  { title:"National Forest Policy", type:"Guide", source:"Government", publisher:"Ministry of Environment, Forest and Climate Change", date:"Policy reference", description:"The policy framework for conservation, ecological stability, forest productivity and community needs in India.", format:"POLICY / PDF", href:"https://moef.gov.in/", accent:"kraft" },
  { title:"India’s Biennial Update Reports to the UNFCCC", type:"Report", source:"Government", publisher:"Ministry of Environment, Forest and Climate Change", date:"Latest submission", description:"National greenhouse-gas inventory material, including land-use and forestry accounting context.", format:"REPORT / PDF", href:"https://moef.gov.in/climate-change/", accent:"green" },
  { title:"Central Pollution Control Board: pulp and paper", type:"Guide", source:"Government", publisher:"Central Pollution Control Board", date:"Sector reference", description:"Official environmental guidance, technical documents and sector programmes concerning pulp and paper mills.", format:"GUIDANCE", href:"https://cpcb.nic.in/", accent:"copper" },
  { title:"Charter 3.0 for water recycling and pollution prevention in pulp and paper", type:"Guide", source:"Government", publisher:"Central Pollution Control Board", date:"Charter 3.0", description:"A technical charter focused on cleaner production, water conservation, recycling and pollution prevention.", format:"PDF", href:"https://cpcb.nic.in/ngrba/Charter-3.0-PulpPaper.pdf", accent:"copper" },
  { title:"Extended Producer Responsibility for plastic packaging", type:"Guide", source:"Government", publisher:"Central Pollution Control Board", date:"Current framework", description:"The official EPR portal and guidance useful when paper packaging contains plastic layers or enters mixed-material systems.", format:"PORTAL / GUIDANCE", href:"https://eprplastic.cpcb.gov.in/", accent:"kraft" },
  { title:"Solid Waste Management Rules", type:"Standard", source:"Government", publisher:"Ministry of Environment, Forest and Climate Change", date:"Current rules", description:"The regulatory foundation for segregation, collection, processing and responsibilities across India’s municipal waste system.", format:"RULES / PDF", href:"https://moef.gov.in/", accent:"sage" },
  { title:"Know Your Standard", type:"Data portal", source:"Standards body", publisher:"Bureau of Indian Standards", date:"Living catalogue", description:"Search Indian Standards by product or subject and inspect the applicable standard before making a technical claim.", format:"SEARCH PORTAL", href:"https://www.bis.gov.in/know-your-standard/?lang=en", accent:"green" },
  { title:"BIS standards for paper and paper products", type:"Standard", source:"Standards body", publisher:"Bureau of Indian Standards", date:"Living catalogue", description:"The official standards catalogue covering paper, board, packaging, test methods and product requirements.", format:"STANDARDS", href:"https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/knowyourstandards/Indian_standards/isdetails", accent:"kraft" },
  { title:"ISO paper, board and pulps standards", type:"Standard", source:"Standards body", publisher:"International Organization for Standardization", date:"Living catalogue", description:"International test methods and specifications used to compare paper, board, pulp and recovered material consistently.", format:"STANDARDS CATALOGUE", href:"https://www.iso.org/committee/45674.html", accent:"sage" },
  { title:"FAO Forestry publications", type:"Data portal", source:"Intergovernmental", publisher:"Food and Agriculture Organization", date:"Living archive", description:"A broad official library on forests, planted forests, forest products, trade, policy and sustainable management.", format:"PUBLICATION ARCHIVE", href:"https://www.fao.org/forestry/publications/1/en", accent:"green" },
  { title:"Global Forest Resources Assessment", type:"Report", source:"Intergovernmental", publisher:"Food and Agriculture Organization", date:"Latest assessment", description:"The global reference for forest extent, condition, management and change, with country reporting and methods.", format:"REPORT / DATA", href:"https://www.fao.org/forest-resources-assessment/en/", accent:"green" },
  { title:"FAOSTAT Forestry Production and Trade", type:"Data portal", source:"Intergovernmental", publisher:"Food and Agriculture Organization", date:"Living database", description:"Country-level production and trade data for pulp, recovered paper, paper and paperboard products.", format:"DATA PORTAL", href:"https://www.fao.org/faostat/en/#data/FO", accent:"copper" },
  { title:"Sustainable Forest Management Toolbox", type:"Toolkit", source:"Intergovernmental", publisher:"Food and Agriculture Organization", date:"Living toolkit", description:"Modules, cases and learning material for understanding practical sustainable forest management.", format:"TOOLKIT", href:"https://www.fao.org/sustainable-forest-management/toolbox/en/", accent:"sage" },
  { title:"Management of planted forests", type:"Guide", source:"Intergovernmental", publisher:"Food and Agriculture Organization", date:"Learning module", description:"A focused module on planning and managing planted forests and their social and environmental considerations.", format:"LEARNING MODULE", href:"https://www.fao.org/sustainable-forest-management/toolbox/modules/management-of-planted-forests/en/", accent:"green" },
  { title:"Responsible management of planted forests: voluntary guidelines", type:"Guide", source:"Intergovernmental", publisher:"Food and Agriculture Organization", date:"Forestry paper", description:"Principles and considerations for productive, socially responsible and environmentally sound planted forests.", format:"GUIDELINES", href:"https://www.fao.org/4/j9256e/j9256e00.htm", accent:"kraft" },
  { title:"Forest products statistics", type:"Data portal", source:"Intergovernmental", publisher:"Food and Agriculture Organization", date:"Living portal", description:"Methods, yearbooks and datasets for interpreting global forest-product production and trade.", format:"DATA / METHODS", href:"https://www.fao.org/forestry/statistics/80938/en/", accent:"copper" },
  { title:"Recovered paper data in FAOSTAT", type:"Data portal", source:"Intergovernmental", publisher:"Food and Agriculture Organization", date:"Living database", description:"Use the forestry production database to compare recovered-paper collection, imports, exports and use by country.", format:"DATA PORTAL", href:"https://www.fao.org/faostat/en/#data/FO", accent:"sage" },
  { title:"The State of the World’s Forests", type:"Report", source:"Intergovernmental", publisher:"Food and Agriculture Organization", date:"Latest edition", description:"A global evidence synthesis on forests, livelihoods, innovation and pathways for forest-sector transformation.", format:"FLAGSHIP REPORT", href:"https://www.fao.org/publications/sofo/en/", accent:"green" },
  { title:"Global Forest Products Facts and Figures", type:"Report", source:"Intergovernmental", publisher:"Food and Agriculture Organization", date:"Latest edition", description:"A concise annual reading of production and trade trends across major wood and paper product groups.", format:"FACTS / PDF", href:"https://www.fao.org/forestry/statistics/80938/en/", accent:"copper" },
  { title:"UNEP Life Cycle Initiative", type:"Toolkit", source:"Intergovernmental", publisher:"United Nations Environment Programme", date:"Living initiative", description:"Methods and resources for life-cycle thinking, useful for comparing systems without shifting impacts between stages.", format:"METHOD TOOLKIT", href:"https://www.lifecycleinitiative.org/", accent:"sage" },
  { title:"Guidelines for Social Life Cycle Assessment", type:"Guide", source:"Intergovernmental", publisher:"United Nations Environment Programme", date:"Method guidance", description:"Guidance for including workers, communities and value-chain stakeholders in life-cycle assessment.", format:"GUIDELINES", href:"https://www.lifecycleinitiative.org/library/guidelines-for-social-life-cycle-assessment-of-products-and-organisations-2020/", accent:"kraft" },
  { title:"Global Waste Management Outlook", type:"Report", source:"Intergovernmental", publisher:"United Nations Environment Programme", date:"Global outlook", description:"A systems view of waste prevention, collection, recovery and governance that helps locate paper within wider material flows.", format:"REPORT", href:"https://www.unep.org/resources/global-waste-management-outlook-2024", accent:"green" },
  { title:"World Bank What a Waste 2.0", type:"Report", source:"Intergovernmental", publisher:"World Bank", date:"Global dataset", description:"Comparable municipal solid-waste data and projections, with composition and collection context across countries.", format:"REPORT / DATA", href:"https://datatopics.worldbank.org/what-a-waste/", accent:"copper" },
  { title:"UN Comtrade Database", type:"Data portal", source:"Intergovernmental", publisher:"United Nations Statistics Division", date:"Living database", description:"Official international trade data for checking flows of pulp, recovered paper, paper and board by commodity code.", format:"TRADE DATA", href:"https://comtradeplus.un.org/", accent:"sage" },
  { title:"Sustainable Development Goal 12 data", type:"Data portal", source:"Intergovernmental", publisher:"United Nations", date:"Living indicator set", description:"Official indicators for responsible consumption and production, material footprint and waste-policy context.", format:"SDG DATA", href:"https://sdgs.un.org/goals/goal12", accent:"kraft" },
];
