"use client";

import { ChevronDown, ChevronUp, Edit3, FilePlus2, RefreshCw, Search, Trash2 } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import MythEditor from "./MythEditor";
import { useAdminAccess } from "./AdminShell";

type MythItem = { _id?: string; claim: string; correction: string; explanation: string; category: string; verdict: "myth" | "fact" | "context"; tags?: string[]; sources?: { label: string; url: string }[]; status?: string; order?: number; coverImage?: string; revisionNote?: string; version?: number };
export default function MythManager() {
  const { canEdit } = useAdminAccess();
  const [items, setItems] = useState<MythItem[]>([]), [editing, setEditing] = useState<MythItem | "new" | null>(null), [notice, setNotice] = useState(""), [query, setQuery] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/myths?status=all"); const data = await response.json(); setItems(data.items ?? []); }, []);
  useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => items.filter(item => `${item.claim} ${item.correction} ${item.category}`.toLowerCase().includes(query.toLowerCase())), [items, query]);
  async function save(data: Record<string, unknown>) { const current = editing && editing !== "new" ? editing : null; const raw = Array.isArray(data.sources) ? data.sources.map(String) : []; const sources = raw.filter(Boolean).map(url => ({ label: url.replace(/^https?:\/\//, "").split("/")[0], url })); const payload = { ...(current?._id ? { id: current._id, expectedVersion: current.version } : {}), claim: data.myth, verdict: data.verdict ?? current?.verdict ?? "context", correction: data.fact, explanation: data.explanation, category: data.category, tags: data.tags, sources, status: data.status, featured: false, order: current?.order ?? items.length, coverImage: data.coverImage, revisionNote: data.revisionNote }; const response = await fetch("/api/myths", { method: current?._id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json(); setNotice(response.ok ? "Myth or fact saved." : result.error); if (response.ok) { setEditing(null); await load(); } }
  async function remove(item: MythItem) { if (!item._id || !confirm("Move this record to recoverable trash?")) return; const response = await fetch(`/api/myths?id=${item._id}`, { method: "DELETE" }); const result = await response.json(); setNotice(response.ok ? "Record moved to trash. Restore it from History & rollback." : result.error ?? "Record could not be deleted."); if (response.ok) await load(); }
  async function move(index: number, direction: number) { const target=index+direction;if(target<0||target>=items.length)return;const next=[...items];[next[index],next[target]]=[next[target],next[index]];setItems(next);const responses=await Promise.all([next[index],next[target]].filter(item=>item._id).map(item=>fetch("/api/myths",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item._id,order:next.indexOf(item),expectedVersion:item.version})})));if(responses.some(response=>!response.ok)){setNotice("Order changed elsewhere. Reloading the latest version.");await load();} }
  return <div><header className="admin-workspace-heading"><div><p>Research publishing</p><h1>Myths and facts</h1></div><div><button className="admin-action" onClick={() => void load()}><RefreshCw /> Refresh</button>{canEdit&&<button className="admin-action primary" onClick={() => setEditing("new")}><FilePlus2 /> New record</button>}</div></header>{notice&&<div className="admin-notice">{notice}</div>}{editing?<section className="admin-editor-panel"><header><div><p>{canEdit?"EDITOR":"READ-ONLY PREVIEW"}</p><h2>{editing==="new"?"New myth or fact":editing.claim}</h2></div><button onClick={()=>setEditing(null)}>Close</button></header><MythEditor initialData={editing==="new"?undefined:{myth:editing.claim,fact:editing.correction,explanation:editing.explanation,category:editing.category,tags:editing.tags??[],sources:(editing.sources??[]).map(source=>source.url),status:editing.status??"draft",coverImage:editing.coverImage,revisionNote:editing.revisionNote,verdict:editing.verdict}} onSave={canEdit?save:undefined}/></section>:<><div className="admin-toolbar"><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search claims, corrections or category"/></label><span>{filtered.length} records</span></div><div className="admin-data-list">{filtered.map(item=>{const index=items.indexOf(item);return <article className="admin-data-row" key={item._id??item.claim}><div><strong>{item.claim}</strong><small>{item.correction}</small></div><span>{item.category} · {item.verdict}</span><em>{item.status??"review"}</em><div className="admin-row-actions">{canEdit&&<><button disabled={!item._id} onClick={()=>void move(index,-1)}><ChevronUp/></button><button disabled={!item._id} onClick={()=>void move(index,1)}><ChevronDown/></button></>}<button onClick={()=>setEditing(item)} title="Inspect or edit"><Edit3/></button>{canEdit&&<button disabled={!item._id} onClick={()=>void remove(item)}><Trash2/></button>}</div></article>})}</div></>}</div>;
}
